import React, { useState } from 'react';
import { Info } from 'lucide-react';

export default function Login({ onLogin }) {
    const [role, setRole] = useState('Employee');

    const handleSubmit = (e) => {
        e.preventDefault();
        onLogin(role);
    };

    return (
        <div className="min-h-screen flex items-center justify-center bg-[#f6f9ff] p-4 font-sans">
            <div className="bg-white p-8 rounded-xl shadow-2xl w-full max-w-md border-t-8 border-[#4154f1]">

                {/* Logo / Brand */}
                <div className="text-center mb-10">
                    <h1 className="text-3xl font-bold text-[#012970] font-display tracking-tight">Dayflow</h1>
                    <p className="text-gray-500 text-sm mt-1">Human Resource Management System</p>
                </div>

                <form onSubmit={handleSubmit} className="space-y-6">

                    {/* Role Toggle */}
                    <div>
                        <label className="block text-xs font-bold text-gray-500 uppercase tracking-wider mb-2">Select Access Role</label>
                        <div className="flex bg-gray-100 p-1 rounded-lg">
                            <button
                                type="button"
                                className={`flex-1 py-2.5 rounded-md text-sm font-bold transition-all ${role === 'Admin' ? 'bg-white shadow-md text-[#4154f1]' : 'text-gray-400 hover:text-gray-600'
                                    }`}
                                onClick={() => setRole('Admin')}
                            >
                                Admin
                            </button>
                            <button
                                type="button"
                                className={`flex-1 py-2.5 rounded-md text-sm font-bold transition-all ${role === 'Employee' ? 'bg-white shadow-md text-[#4154f1]' : 'text-gray-400 hover:text-gray-600'
                                    }`}
                                onClick={() => setRole('Employee')}
                            >
                                Employee
                            </button>
                        </div>
                    </div>

                    {/* Login ID */}
                    <div className="group relative">
                        <div className="flex justify-between items-center mb-1">
                            <label className="block text-sm font-semibold text-[#012970]">Login ID / Email</label>
                            <Info size={14} className="text-[#4154f1] cursor-help" />
                        </div>

                        {/* Tooltip implementation from Wireframe */}
                        <div className="hidden group-hover:block absolute right-0 top-0 transform -translate-y-full mb-2 w-64 p-3 bg-slate-800 text-white text-xs rounded shadow-lg z-10">
                            <p className="font-bold mb-1 border-b border-slate-600 pb-1">Format: IOI + Name + Year + Serial</p>
                            <p>Example: <strong>IOIROSHAN20220001</strong></p>
                            <p className="mt-1 opacity-75">Auto-generated by HR System.</p>
                        </div>

                        <input
                            type="text"
                            placeholder="e.g. IOIROSHAN20220001"
                            value="demo.user"
                            readOnly
                            className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:border-[#4154f1] focus:ring-4 focus:ring-blue-50 transition-all text-gray-700 bg-gray-50"
                        />
                    </div>

                    {/* Password */}
                    <div>
                        <label className="block text-sm font-semibold text-[#012970] mb-1">Password</label>
                        <input
                            type="password"
                            placeholder="••••••••"
                            value="password"
                            readOnly
                            className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:border-[#4154f1] focus:ring-4 focus:ring-blue-50 transition-all text-gray-700 bg-gray-50"
                        />
                    </div>

                    {/* Submit */}
                    <button
                        type="submit"
                        className="w-full bg-gradient-to-r from-[#4154f1] to-[#2a37c9] text-white py-3 rounded-lg font-bold hover:shadow-lg hover:shadow-blue-500/40 transition-all transform hover:-translate-y-0.5"
                    >
                        Sign In
                    </button>

                    <div className="text-center mt-6">
                        <p className="text-xs text-gray-400">
                            Don't have an account? <span className="text-gray-400 cursor-not-allowed">Contact HR</span>
                        </p>
                    </div>
                </form>
            </div>
        </div>
    );
}
